from pyside6_ios.config import AppConfig

TEMPLATE = """\
// Generated by pyside6-ios. Do not edit.
#pragma push_macro("slots")
#undef slots
#include <Python.h>
#pragma pop_macro("slots")

#import <UIKit/UIKit.h>

#include <QtGui/QGuiApplication>
#include <QtGui/QWindow>
#include <QtCore/QDebug>
#include <QtCore/QtPlugin>

Q_IMPORT_PLUGIN(QIOSIntegrationPlugin)
{qml_plugin_imports}
{extern_decls}

static QGuiApplication *qtApp = nullptr;

static void initPython() {{
    NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
    NSString *stdlibPath = [bundlePath stringByAppendingPathComponent:@"lib/python{python_version}"];
    NSString *dynloadPath = [stdlibPath stringByAppendingPathComponent:@"lib-dynload"];
{search_path_decls}

{inittab_calls}

    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);
    config.write_bytecode = 0;
    config.home = Py_DecodeLocale([bundlePath UTF8String], NULL);

    config.module_search_paths_set = 1;
    PyWideStringList_Append(&config.module_search_paths,
        Py_DecodeLocale([stdlibPath UTF8String], NULL));
    PyWideStringList_Append(&config.module_search_paths,
        Py_DecodeLocale([dynloadPath UTF8String], NULL));
{search_path_appends}

    PyStatus status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status)) {{
        NSLog(@"Python init failed: %s", status.err_msg);
        return;
    }}
    NSLog(@"Python %s initialized", Py_GetVersion());
}}

static void runPythonApp() {{
    NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
    NSString *scriptPath = [bundlePath stringByAppendingPathComponent:@"scripts/app.py"];

    FILE *fp = fopen([scriptPath UTF8String], "r");
    if (!fp) {{
        NSLog(@"Failed to open %@", scriptPath);
        return;
    }}
    NSLog(@"Running Python script...");
    int result = PyRun_SimpleFile(fp, [scriptPath UTF8String]);
    fclose(fp);
    if (result != 0) {{
        NSLog(@"Python script failed with code %d", result);
        if (PyErr_Occurred()) PyErr_Print();
    }}
}}

@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation SceneDelegate
- (void)scene:(UIScene *)scene
    willConnectToSession:(UISceneSession *)session
    options:(UISceneConnectionOptions *)connectionOptions {{

    UIWindowScene *windowScene = (UIWindowScene *)scene;
    self.window = [[UIWindow alloc] initWithWindowScene:windowScene];
    self.window.backgroundColor = [UIColor blackColor];
    self.window.rootViewController = [[UIViewController alloc] init];
    [self.window makeKeyAndVisible];

    initPython();

    static int argc = 1;
    static const char *argv[] = {{"{app_name}", nullptr}};
    qtApp = new QGuiApplication(argc, const_cast<char **>(argv));
    qDebug() << "Qt" << qVersion() << "platform:" << qtApp->platformName();

    runPythonApp();

    dispatch_async(dispatch_get_main_queue(), ^{{
        QWindowList windows = QGuiApplication::topLevelWindows();
        if (!windows.isEmpty()) {{
            QWindow *qtWindow = windows.first();
            WId nativeId = qtWindow->winId();
            UIView *qtView = (__bridge UIView *)(void *)nativeId;
            if (qtView) {{
                qtView.frame = self.window.bounds;
                qtView.autoresizingMask = UIViewAutoresizingFlexibleWidth |
                                          UIViewAutoresizingFlexibleHeight;
                [self.window.rootViewController.view addSubview:qtView];
                qDebug() << "Reparented Qt view into iOS window";
            }}
        }}
    }});
}}
@end

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@end

@implementation AppDelegate
- (UISceneConfiguration *)application:(UIApplication *)application
    configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession
    options:(UISceneConnectionOptions *)options {{
    UISceneConfiguration *config =
        [[UISceneConfiguration alloc] initWithName:@"Default"
                                       sessionRole:connectingSceneSession.role];
    config.delegateClass = [SceneDelegate class];
    return config;
}}
@end

int main(int argc, char *argv[]) {{
    @autoreleasepool {{
        return UIApplicationMain(argc, argv, nil,
            NSStringFromClass([AppDelegate class]));
    }}
}}
"""


def generate(cfg: AppConfig) -> str:
    extern_lines = []
    inittab_lines = []

    # PySide6 modules
    for mod in cfg.pyside6_modules:
        extern_lines.append(f'extern "C" PyObject *PyInit_{mod}();')
        inittab_lines.append(
            f'    PyImport_AppendInittab("PySide6.{mod}", PyInit_{mod});'
        )

    # Shiboken runtime
    extern_lines.append('extern "C" PyObject *PyInit_Shiboken();')
    inittab_lines.append(
        '    PyImport_AppendInittab("shiboken6.Shiboken", PyInit_Shiboken);'
    )

    # Custom binding modules
    for bmod in cfg.binding_modules:
        init_name = bmod.name.lstrip("_")
        extern_lines.append(f'extern "C" PyObject *PyInit_{init_name}();')
        inittab_lines.append(
            f'    PyImport_AppendInittab("{bmod.name}", PyInit_{init_name});'
        )

    # Python search paths
    search_path_decls = []
    search_path_appends = []

    path_entries = [
        ("appScriptsPath", "scripts"),
        ("appPackagesPath", "packages"),
    ]
    if cfg.vendor_dir:
        path_entries.append(("appVendorPath", "vendor"))

    for var_name, subdir in path_entries:
        search_path_decls.append(
            f'    NSString *{var_name} = [bundlePath stringByAppendingPathComponent:@"{subdir}"];'
        )
        search_path_appends.append(
            f"    PyWideStringList_Append(&config.module_search_paths,\n"
            f"        Py_DecodeLocale([{var_name} UTF8String], NULL));"
        )

    qml_import_lines = []
    for plugin in cfg.qml_plugins:
        qml_import_lines.append(f"Q_IMPORT_PLUGIN({plugin.classname})")

    app_name = cfg.name.replace('"', '\\"').replace(" ", "")

    return TEMPLATE.format(
        extern_decls="\n".join(extern_lines),
        qml_plugin_imports="\n".join(qml_import_lines),
        python_version=cfg.python_version,
        search_path_decls="\n".join(search_path_decls),
        inittab_calls="\n".join(inittab_lines),
        search_path_appends="\n".join(search_path_appends),
        app_name=app_name,
    )
